// Bespoke templates for the marketing pages (partners, bills, about, contact,
// careers). Copy is curated from the live pages on unihomes.co.uk — keep it
// faithful to the live wording rather than inventing claims.
import { esc, href, live, img, icon, stars, breadcrumb, base, fmtDate } from '../shared/ui.js';

const CDN0 = 'https://cdn-p0.unihomes.co.uk';
const WP = 'https://landing.unihomes.co.uk/wp-content/uploads';
const head = () => `<link rel="stylesheet" href="${base()}/assets/css/marketing.css">`;
const num = (n) => Number(n || 0).toLocaleString('en-GB');
const crumbs = (name) => breadcrumb([{ name: 'Home', path: '/' }, { name }]);

// ------------------------------------------------------------ building blocks

const hero = ({ eyebrow, title, lead, actions = '', extra = '', name, image }) => `
<section class="page-hero mk-hero${image ? ' has-img' : ''}">${image ? `<img class="bg" src="${esc(image)}" alt="" fetchpriority="high">` : ''}<div class="wrap">
  ${crumbs(name)}
  ${eyebrow ? `<p class="mk-eyebrow">${esc(eyebrow)}</p>` : ''}
  <h1>${esc(title)}</h1>
  ${lead ? `<p>${esc(lead)}</p>` : ''}
  ${actions ? `<div class="mk-actions">${actions}</div>` : ''}
  ${extra}
</div></section>`;

const statRow = (stats) =>
  `<div class="stat-row">${stats.map(([v, l]) => `<div class="stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}</div>`;

const sectionHead = (eyebrow, title, lead) =>
  `<div class="mk-head">${eyebrow ? `<p class="mk-eyebrow mk-eyebrow-dark">${esc(eyebrow)}</p>` : ''}<h2>${esc(title)}</h2>${lead ? `<p>${esc(lead)}</p>` : ''}</div>`;

const tiles = (items, cols = 'three') =>
  `<div class="tiles ${cols}">${items
    .map(
      (t) =>
        `<div class="tile">${t.icon ? `<span class="ti">${t.iconImg ? `<img src="${esc(t.iconImg)}" alt="" width="24" height="24" loading="lazy">` : icon(t.icon)}</span>` : ''}${t.stat ? `<p class="mk-tile-stat">${esc(t.stat)}</p>` : ''}<h3>${esc(t.title)}</h3><p>${esc(t.text)}</p>${t.quote ? `<blockquote class="mk-tile-quote"><p>“${esc(t.quote)}”</p><footer>${esc(t.by)}</footer></blockquote>` : ''}</div>`,
    )
    .join('')}</div>`;

const steps = (items, cls = '') =>
  `<ol class="steps ${cls}">${items.map(([t, d]) => `<li><h3>${esc(t)}</h3><p>${esc(d)}</p></li>`).join('')}</ol>`;

const faq = (items) =>
  `<div class="faq">${items.map(([q, a]) => `<details><summary>${esc(q)}${icon('chevronDown')}</summary><div class="faq-a"><p>${esc(a)}</p></div></details>`).join('')}</div>`;

const quotes = (items) =>
  `<div class="reviews mk-quotes">${items
    .map(([q, who, meta]) => `<figure class="review mk-quote"><blockquote><p>“${esc(q)}”</p></blockquote><figcaption><strong>${esc(who)}</strong>${meta ? `<span>${esc(meta)}</span>` : ''}</figcaption></figure>`)
    .join('')}</div>`;

const barChart = (rows, source) =>
  `<div class="mk-chart"><p class="mk-chart-title">Percentage of student enquiries generated by platform</p><div class="bar-chart">${rows
    .map(([name, v], i) => `<div${i === 0 ? ' class="us"' : ''}><span>${esc(name)}</span><i><b style="width:${v}%"></b></i><strong>${v}%</strong></div>`)
    .join('')}</div><p class="mk-source">${esc(source)}</p></div>`;

const logos = (items, cls = '') =>
  `<ul class="mk-logos ${cls}">${items.map(([src, alt]) => `<li><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy"></li>`).join('')}</ul>`;

const reviewsRail = (r) =>
  r?.items?.length
    ? `<section class="section"><div class="wrap">
  <div class="section-head"><div><h2>What students are saying about us</h2><div class="tp-score">${stars(r.stars || 5)}<strong>${esc(r.score)} out of 5</strong><span class="muted">based on ${num(r.total)} Trustpilot reviews</span></div></div><a class="link-arrow hide-sm" href="${esc(r.url)}" rel="noopener">Read reviews ${icon('external')}</a></div>
  <div class="reviews">${r.items
    .slice(0, 10)
    .map((v) => `<article class="review">${stars(v.stars)}<h3>${esc(v.title)}</h3><p>${esc(v.text)}</p><footer>${esc(v.name)} · ${fmtDate(v.date)}</footer></article>`)
    .join('')}</div>
</div></section>`
    : '';

const SHARED_CHART = [
  ['UniHomes', 57],
  ['Rightmove', 17],
  ['Own website', 12],
  ['Zoopla', 7],
  ['OnTheMarket', 3],
];

// --------------------------------------------------------- letting agents

export function partnerAgents({ pg, site }) {
  const demo = live('/partner-with-us#partner-enquiry');
  const body = `
${hero({
  name: 'Letting agents',
  eyebrow: 'For UK letting agents',
  title: 'Fill faster. Work smarter. Earn more.',
  lead: 'Since 2015, UniHomes has helped letting agents across the UK fill their student properties faster, remove the hassle of utility management and unlock a new revenue stream.',
  actions: `<a class="btn btn-accent btn-lg" href="${demo}">Book a demo</a><a class="btn btn-white btn-lg" href="#how-it-works">How it works</a>`,
  extra: statRow([
    ['91%', 'of partner agents recommend us'],
    ['9.7/10', 'agent satisfaction rating'],
    ['350,000+', 'enquiries generated annually'],
    ['2m+', 'students visit the platform each year'],
  ]),
})}
<nav class="guide-nav" aria-label="On this page"><div class="wrap"><ul>
  <li><a href="#why-unihomes">Why UniHomes</a></li><li><a href="#trusted-by">Trusted by</a></li><li><a href="#what-you-get">What you get</a></li><li><a href="#how-it-works">How it works</a></li><li><a href="#student-packages">Student packages</a></li><li><a href="#tools-portal">Tools &amp; portal</a></li><li><a href="#faqs">FAQs</a></li>
</ul></div></nav>

<section class="section" id="why-unihomes"><div class="wrap mk-split">
  <div>
    ${sectionHead('The home of stress-free student lettings', 'Your pathway to faster lets.')}
    <p>Today's students expect the same from accommodation as they do from everything else: simplicity, transparency, and zero stress. UniHomes was built around that expectation, which is why we've become the go-to place for students searching for a new home.</p>
    <p>Our partner agents tell us we outperform all other major platforms when it comes to generating high-intent student enquiries.</p>
    <div class="mk-minis">
      <div class="mk-mini"><strong>67%</strong><span>of students prefer bills-included accommodation</span></div>
      <div class="mk-mini"><strong>89%</strong><span>of letting agents agree bills-included properties let faster than rent-only</span></div>
    </div>
    <a class="btn btn-primary" href="${demo}">Partner with us</a>
  </div>
  ${barChart(SHARED_CHART, 'UniHomes Client Survey 2026')}
</div></section>

<section class="section section-soft" id="trusted-by"><div class="wrap">
  ${sectionHead('Trusted by letting agents across the UK', 'The partners filling first.', "Most letting agents can't justify building a full in-house marketing team — the channels move too fast, the audience changes too frequently, and the cost keeps growing. Here's how our partner agents are benefitting.")}
  ${quotes([
    ['UniHomes is our most effective online advertising platform for student accommodation. The enquiries received are faultless and the portal is easy to use.', 'JC Lettings and Property Management Limited', 'Sheffield · 130+ properties'],
    ['Advertising with UniHomes has made our letting process significantly smoother. We would recommend their services to any agency letting to students!', 'Zest', 'Bath · 270+ properties'],
    ['We’ve been blown away with the amount of enquiries that UniHomes has generated for us and we cannot recommend them enough.', 'PJ Properties', 'Sheffield · 100+ properties'],
    ["UniHomes is simple to use from the agent portal side, we're able to get adverts up and running with ease. It's become the go-to place for advertising to student tenants.", 'Burrow Property Services', 'Norwich · 10+ properties'],
    ['Advertising properties on UniHomes has been a smooth and pleasant experience - the platform is simple to use, very intuitive, and enquiries come in quickly.', 'Jamal Property World', 'Scotland · 50+ properties'],
    ['UniHomes provide an excellent service to both landlord and tenant. Their customer service is excellent, and very good value. Highly recommended by PC Properties.', 'PC Properties', 'Sheffield · 50+ properties'],
    ['The UniHomes website provides us with lots of enquiries, making letting much easier. The team are very helpful and nothing is too much trouble.', 'MBA Lettings', 'Sheffield · 180+ properties'],
    ['The team are always prompt in replying to our queries. The online dashboard is very user friendly. We wouldn’t hesitate in recommending UniHomes.', 'Thornsett Properties', 'Sheffield · 70+ properties'],
    ['As a letting agent, I couldn’t recommend them enough. We receive a lot of enquiries through UniHomes and have found them very helpful.', 'Aston Properties', 'Leeds · 150+ properties'],
    ['We get detailed information on prospective tenants who are serious about finding a property, which makes the process super smooth.', 'Red Ridge Residential', 'Newcastle upon Tyne · 30+ properties'],
    ['For the last 5 years, we have always used UniHomes. We have seen a massive increase in enquiries over the years!', 'Dove Properties', 'Sheffield · 410+ properties'],
    ['UniHomes have generated more leads for my business than any of the other leading companies. I have been delighted with the professional service they have given over the last year.', 'Daley Lettings', 'Newcastle upon Tyne · 70+ properties'],
  ])}
</div></section>

<section class="section" id="what-you-get"><div class="wrap">
  ${sectionHead("Why we're first choice for agents", 'Built to fill your properties and save you time.')}
  ${tiles([
    { icon: 'mail', stat: '350,000+', title: 'Receive high-quality enquiries to fill your properties.', text: 'We deliver 350,000+ high-quality student enquiries to our partner agents annually.' },
    {
      icon: 'clock',
      stat: '6+ weeks',
      title: 'Reduce operational pressure.',
      text: 'Over 6 weeks saved every year on utility admin, freeing up your team to focus on what matters most.',
      quote: 'Their seamless, hassle-free system means no more chasing payments or dealing with confusing splits - everything is managed smoothly behind the scenes.',
      by: 'Harringtons Lettings, Brighton · 150+ properties',
    },
    {
      icon: 'graduation',
      stat: '67%',
      title: 'Enhanced marketability with an all-inclusive service.',
      text: '67% of students prefer bills-included accommodation. Tap into an audience actively seeking this type of accommodation.',
      quote: 'Tenants prefer to have bills included - it’s great to have all bills under one umbrella and to be able to forward the students to UniHomes and know that their issue will be dealt with.',
      by: 'Headingley Property Services, Leeds · 90+ properties',
    },
  ])}
</div></section>

<section class="section section-soft" id="how-it-works"><div class="wrap">
  ${sectionHead('How it works', '4 steps to stress-free student lettings.', 'Advertise your properties via the UniHomes platform at a bills-included monthly price. From there we deliver high-quality enquiries and, for your secured tenancies, facilitate full utility set-up and management.')}
  ${steps(
    [
      ['Advertise your properties', 'List your student properties at a clear, bills-included monthly price, with utilities calculated and added automatically.'],
      ['Receive high-quality enquiries', 'We provide high-intent enquiries from students actively searching for bills-included accommodation within your city.'],
      ['Stress-free utility management', "We provide an all-inclusive utility management service that is rated 'Excellent' on Trustpilot with over 8,000 reviews."],
      ['Earn uncapped commission', 'All the ways of working with UniHomes provide an opportunity for agents to earn uncapped referral commission.'],
    ],
    'steps-4',
  )}
  <div class="mk-head" style="margin-top:44px">${sectionHead('Choose your billing model', 'The different ways to work with UniHomes.')}</div>
  <div class="mk-billing">
    <div class="mk-bill mk-bill-orange"><p class="mk-eyebrow mk-eyebrow-dark">We support the student</p><h3>Student Billing</h3><ul class="features">${[
      'You list your properties on the UniHomes platform and receive high-intent student enquiries.',
      'You conduct your normal letting process, communicating the all-inclusive rate, and refer successful tenancies to a UniHomes Utility Order Form.',
      'Tenants sign our Utility Order Form, and we act as their direct point of contact for utilities.',
      'Students deal directly with our team for every utility query, keeping utility admin off your plate entirely.',
      'You earn referral commission for every student who signs up to a utility package.',
    ]
      .map((t) => `<li>${icon('check')}<span>${esc(t)}</span></li>`)
      .join('')}</ul></div>
    <div class="mk-bill"><p class="mk-eyebrow mk-eyebrow-dark">We support you</p><h3>Agent Billing</h3><ul class="features">${[
      'You sign a UniHomes Utility Order Form for every successful tenancy and maintain direct control of tenant utility relationships.',
      'We become your single point of contact for utility queries.',
      'Fixed utility pricing helps you budget and forecast effectively.',
      'Build a repeatable income stream that scales with your portfolio.',
    ]
      .map((t) => `<li>${icon('check')}<span>${esc(t)}</span></li>`)
      .join('')}</ul></div>
  </div>
</div></section>

<section class="section" id="student-packages"><div class="wrap">
  ${sectionHead('Experts in utility management', 'Packages built for students - and your properties.', 'Our utility packages are built to address the pressures students face today. Our stress-free promise goes beyond just all-inclusive living.')}
  <div class="mk-split mk-split-img">
    <img class="mk-photo" src="${CDN0}/images/partners/students-on-bed.jpg" alt="Students relaxing at home — all utilities included" loading="lazy">
    ${tiles(
      [
        { icon: 'layers', title: 'All utilities. One account.', text: 'We handle household utilities end-to-end, setting up, managing and bundling everything into one simple monthly payment. No chief bill payer, no deposits, no setup fees, and no drama.' },
        { icon: 'flame', title: 'Gas & Electricity (Uncapped).', text: 'Uncapped energy is included as standard, so tenants can live comfortable without the stress of over-usage bills. It also keeps properties warm and mitigates the risk of damp and mould.' },
        { icon: 'wifi', title: 'Superfast broadband.', text: 'We work with leading UK providers Virgin Media and BT to deliver superfast broadband as standard, so tenants can stream, game and study without worries.' },
        { icon: 'phone', title: 'UK support, based in Sheffield.', text: "Students deal directly with our 'Excellent' Trustpilot-rated support team, based at our Sheffield offices." },
      ],
      'mk-tiles-2',
    )}
  </div>
  <div class="mk-logo-block">
    <h3>Premium suppliers choose to work with us.</h3><p class="muted">When a tenant moves in, they're connected to:</p>
    ${logos([
      [`${CDN0}/images/partners/leading-suppliers-british-gas.png`, 'British Gas'],
      [`${CDN0}/images/partners/leading-suppliers-virgin-media.png`, 'Virgin Media'],
      [`${CDN0}/images/partners/leading-suppliers-bt.png`, 'BT'],
      [`${CDN0}/images/partners/leading-suppliers-pine-media.svg`, 'Pine Media'],
    ])}
  </div>
</div></section>

<section class="section section-soft" id="tools-portal"><div class="wrap">
  ${sectionHead('CRM integrations', 'Built to fit with your existing workflows.', 'We integrate with all major CRM providers to ensure your UniHomes partnership is as simple and friction-free as possible.')}
  ${logos(
    [
      ['crm-reapit.svg', 'Reapit'],
      ['crm-agentos.svg', 'agentOS'],
      ['crm-sme-professional.svg', 'SME Professional'],
      ['crm-mri.svg', 'MRI Software'],
      ['crm-alto.svg', 'Alto'],
      ['crm-street.svg', 'Street'],
      ['crm-gnb-property.svg', 'GNB Property Software'],
      ['crm-arthur.png', 'Arthur'],
      ['crm-vebra.png', 'Vebra'],
      ['crm-hybr.svg', 'Hybr'],
    ].map(([f, a]) => [`${CDN0}/images/partners/${f}`, a]),
    'mk-logos-crm',
  )}
  <div style="margin-top:44px">${sectionHead('Built for performance', 'Everything you need to optimise and grow your portfolio.', "From real-time performance data to ready-made marketing assets and a dedicated support team, you'll have everything you need to succeed and stay ahead.")}</div>
  ${tiles([
    { icon: 'layers', title: 'Data and insights', text: 'Detailed performance insights across your portfolio based on our wider marketplace, helping you optimise pricing, visibility and enquiry conversion.' },
    { icon: 'sparkles', title: 'Tools for success', text: 'Marketing materials and city-specific platform insights to help your team maximise performance.' },
    { icon: 'user', title: 'Expert support teams', text: 'Client Growth Managers and business support teams help you fill properties, unlock revenue and access quick, effective help whenever needed.' },
  ])}
</div></section>

<section class="section" id="faqs"><div class="wrap mk-split mk-split-faq">
  <div>${sectionHead('FAQs', 'Frequently asked questions.', "Partnering with UniHomes is simple and straightforward, often taking only a matter of days. With that said, we've earmarked a few frequently asked questions to get you started.")}<a class="btn btn-outline" href="${demo}">Speak to our team</a></div>
  ${faq([
    ['How can I advertise student accommodation on UniHomes?', 'There are several different ways of working with us, all of which are simple and easy to set-up. You are able to list your properties with us either manually or via your chosen CRM provider. We integrate with all major CRM systems to ensure seamless property listing.'],
    ['What are the best places to advertise student accommodation?', "UniHomes is the UK's leading bills-included student accommodation platform, reaching millions of students each year. Partner agents also benefit from CRM integrations and high-intent student traffic driven by our student-first brand."],
    ['How does UniHomes work for letting agents?', 'Advertise your properties at a bills-included monthly price, receive high-quality enquiries, and refer secured tenancies for utility set-up. Choose student or agent billing depending on how much of the tenant relationship you want to retain.'],
  ])}
</div></section>

${demoBand({
  title: 'Partner with UniHomes.',
  sub: 'Book your 20-minute demo. A member of our team will be in touch at your chosen time.',
  points: ['Discussion tailored to your portfolio', 'Platform walkthrough included', 'No commitment, no setup fees, no obligation'],
  cta: 'Book a demo',
  url: demo,
})}`;
  return { title: pg?.meta?.title || 'Advertise Student Properties | Letting Agents | UniHomes', description: pg?.meta?.description, body, head: head() };
}

function demoBand({ title, sub, points, cta, url }) {
  return `<section class="section-tight mk-demo-wrap"><div class="wrap"><div class="mk-demo">
  <div><h2>${esc(title)}</h2><p>${esc(sub)}</p><ul class="mk-ticks">${points.map((p) => `<li>${icon('check')}${esc(p)}</li>`).join('')}</ul></div>
  <div class="mk-demo-cta"><a class="btn btn-accent btn-lg" href="${url}">${esc(cta)} ${icon('arrowRight')}</a><p>Opens the enquiry form on unihomes.co.uk</p></div>
</div></div></section>`;
}

// ---------------------------------------------------------------- PBSA / BTR

export function partnerPbsa({ pg }) {
  const call = live('/partner-with-us-pbsa#landlord-enquiry');
  const body = `
${hero({
  name: 'PBSA & BTR operators',
  eyebrow: 'For PBSA & build-to-rent operators',
  title: 'Turn searching renters into secured bookings.',
  lead: "UniHomes is one of the UK's most established marketplaces, connecting providers with over 2 million active home hunters every year.",
  actions: `<a class="btn btn-accent btn-lg" href="${call}">Request a call</a><a class="btn btn-white btn-lg" href="#first-for-operators">Why operators choose us</a>`,
  extra: statRow([
    ['12M+', 'on-site searches'],
    ['375,000+', 'enquiries generated annually'],
    ['89%', 'UK-based visitors'],
    ['2M+', 'students visit the platform each year'],
  ]),
})}
<nav class="guide-nav" aria-label="On this page"><div class="wrap"><ul>
  <li><a href="#why-unihomes">Why UniHomes</a></li><li><a href="#what-our-partners-say">What our partners say</a></li><li><a href="#first-for-operators">First for operators</a></li><li><a href="#marketing">Marketing</a></li><li><a href="#faqs">FAQs</a></li>
</ul></div></nav>

<section class="section" id="why-unihomes"><div class="wrap mk-split">
  <div>
    ${sectionHead('Why students choose UniHomes', 'Your shortcut to faster lets.')}
    <p>Today's renters choose where to live the way they choose everything else - quickly, transparently, online. UniHomes was built around that expectation, which is why we've become the first place students go when searching for a home.</p>
    <div class="mk-minis mk-minis-3">
      ${[
        ['2M+', 'students visit the platform each year'],
        ['1.5M', 'organic search visits in 2025'],
        ['89%', 'UK-based, pre-qualified audience'],
        ['20% YoY', 'growth in 1-bed property searches from 2025 to 2026'],
        ['12M+', 'annual on-site searches'],
        ['375K+', 'annual enquiries generated'],
      ]
        .map(([v, l]) => `<div class="mk-mini"><strong>${v}</strong><span>${l}</span></div>`)
        .join('')}
    </div>
  </div>
  ${barChart(SHARED_CHART, 'UniHomes Client Survey 2026')}
</div></section>

<section class="section section-soft" id="what-our-partners-say"><div class="wrap">
  ${sectionHead('What our partners say', 'Trusted by operators across the UK.')}
  ${quotes([
    ['Tenants go to UniHomes first. From onboarding to continued support, UniHomes have been impressive. The platform is incredibly easy to use and has generated lots of quality leads. It was the obvious choice as we explored our marketplace options.', 'Customer Experience Director', 'Homie'],
    ["They reach an audience other platforms don't. As a PBSA operator, we're looking forward to working with UniHomes in an agent referral capacity. Their team have been fantastic - very professional and a pleasure to work with.", 'Sales & Leasing Manager', 'Yugo'],
    ["UniHomes have been brilliant from the outset. Launching on their platform, combined with the team's excellent communication and support, has allowed us to showcase all our UK properties to more students. We're excited to continue working together.", 'Head of Sales', 'True Student'],
    ["Within two weeks, we'd converted enquiries. The implementation was easy and straightforward. The team were approachable and responsive, and within the first two weeks we received a number of really good enquiries that suited our accommodation and easily converted into bookings.", 'Sales Director', 'Nurtur Student Living'],
  ])}
</div></section>

<section class="section" id="first-for-operators"><div class="wrap">
  ${sectionHead('Why we’re first choice for operators', 'Built to fill your rooms and protect your occupancy.', 'Advertise your buildings via the UniHomes platform and receive high-intent enquiries from house hunting students delivered directly to your team.')}
  ${tiles(
    [
      { iconImg: `${CDN0}/images/pbsa/icon-student.svg`, icon: 'graduation', title: 'High-intent enquiries', text: "Our pre-qualified student audience search and enquire directly through your listings, so every lead arrives with context on who they are and what they're looking for." },
      { iconImg: `${CDN0}/images/pbsa/icon-trend-up.svg`, icon: 'layers', title: 'Growing demand for your portfolio', text: 'Searches for 1-bedroom properties grew 20% year-on-year from 2025 to 2026 - the fastest-growing segment in our marketplace - while student demand stays strong across 70+ UK cities.' },
      { iconImg: `${CDN0}/images/pbsa/icon-monitor-play.svg`, icon: 'play', title: 'An award-winning marketing engine', text: 'Our multi-channel strategy drives consistent student traffic to the platform all year round, ensuring your listings are seen by an actively searching audience.' },
      { iconImg: `${CDN0}/images/pbsa/icon-chart-bar.svg`, icon: 'sliders', title: 'Benchmark with portfolio-wide intelligence', text: 'Compare your pricing, visibility and enquiry conversion against the wider UniHomes ecosystem - city by city, building by building.' },
    ],
    'four',
  )}
</div></section>

<section class="section-tight" id="marketing"><div class="wrap"><div class="mk-reach">
  <div>
    <p class="mk-eyebrow">Marketing reach</p>
    <h2>Your outsourced marketing department - with zero headcount cost.</h2>
    <p>The student audience moves fast, lives on different channels, and responds to different creative. Our multi-channel strategy is built around exactly that, driving consistent student traffic to the platform all year round. List with us and your portfolio sits inside that reach - no agency retainer, no media buying overhead.</p>
    ${statRow([
      ['320M+', 'brand impressions / year'],
      ['2M+', 'platform visitors / year'],
    ])}
  </div>
  <ul class="mk-ticks mk-ticks-light">${[
    'Paid digital advertising and retargeting',
    'National network of brand and content ambassadors',
    'Influencer collaborations across the UK student creator network',
    'Always-on social campaigns — TikTok, Instagram, YouTube',
    'Out-of-home activity in major UK university cities',
    'Freshers fairs and on-campus events',
    'Brand collaborations with student lifestyle partners',
  ]
    .map((t) => `<li>${icon('check')}${esc(t)}</li>`)
    .join('')}</ul>
</div></div></section>

<section class="section" id="data-insight-support"><div class="wrap">
  ${sectionHead('Data, insight and support', 'Everything you need to optimise and grow your portfolio.', "From real-time performance data to ready-made marketing assets and a dedicated support team, you'll have everything you need to succeed and stay ahead.")}
  ${tiles([
    { iconImg: `${CDN0}/images/pbsa/icon-chart-bar.svg`, icon: 'layers', title: 'Data and insights', text: 'Detailed performance dashboards across your portfolio and the wider UniHomes marketplace, helping you optimise visibility and conversion in every city you operate in.' },
    { iconImg: `${CDN0}/images/pbsa/icon-handshake.svg`, icon: 'user', title: 'Dedicated Account Manager', text: 'On hand for regular performance reviews, listing optimisation and strategic input. One point of contact, not a ticketing queue.' },
    { iconImg: `${CDN0}/images/pbsa/icon-compass-rose.svg`, icon: 'sparkles', title: 'Tools to maximise opportunity', text: 'Marketing materials, city insight packs, educational webinars and ready-made creative that helps you convert faster.' },
  ])}
</div></section>

<section class="section section-soft" id="faqs"><div class="wrap mk-split mk-split-faq">
  <div>${sectionHead('FAQs', 'Frequently asked questions.', "Partnering with UniHomes is simple and straightforward, often taking only a matter of days. With that said, we've earmarked a few frequently asked questions to get you started.")}<a class="btn btn-outline" href="${call}">Speak to our team</a></div>
  ${faq([
    ['Is UniHomes for PBSA, BTR or both?', 'Both. We work with operators across the full spectrum - from large PBSA portfolios with cluster flats and studios, to BTR schemes with 1-beds, 2-beds and amenity-led living. The marketing reach is shared; the listing experience is tailored to each product type.'],
    ['Do you only market to students?', 'No. Students are the core of our audience, but it also includes a fast-growing population of postgraduates, graduates and young professionals. These are the demographics typically filling 1-bed and studio stock.'],
    ['How are enquiries qualified?', "Renters search and enquire directly through your listing, so each enquiry arrives with context on who they are and what they're looking for."],
    ['How long does onboarding take?', "Most operators are live and listing in under two weeks. The platform integrates into your existing CRM, so there's no rebuild and no retraining."],
    ['Which CRMs do you integrate with?', 'We integrate with all major CRM providers to ensure your UniHomes partnership is as simple and friction-free as possible. Speak to our team for the latest list of supported integrations.'],
    ['What does it cost?', 'Listing models vary by portfolio size, product type and city mix. Speak to our team for a tailored proposal.'],
  ])}
</div></section>

${demoBand({
  title: 'Partner with UniHomes.',
  sub: 'A member of our team will be in touch to walk you through how UniHomes can fill your buildings faster, cut your void days, and put your portfolio in front of 2 million+ active renters.',
  points: ['PBSA and build-to-rent', 'Live and listing in under two weeks', 'Integrates with your existing CRM'],
  cta: 'Request a call',
  url: call,
})}`;
  return { title: pg?.meta?.title || 'PBSA & Build-to-Rent Operators | UniHomes', description: pg?.meta?.description, body, head: head() };
}

// --------------------------------------------------------------------- bills

export function bills({ pg, site }) {
  const quote = 'https://join.unihomes.co.uk/';
  const r = site?.reviews;
  const guides = [
    ['/blog/everything-you-need-to-know-about-student-energy-bills', 'Everything You Need to Know About Student Energy Bills', 'blog/everything-you-need-to-know-about-student-energy-bills-yjz.jpg'],
    ['/blog/what-I-wish-I-had-known-about-student-bills', '7 Things I Wish I Knew About Student Bills Before Starting Uni', 'blog/what-I-wish-I-had-known-about-student-bills-tsf.jpg'],
    ['/blog/student-bills-packages-vs-doing-it-yourself', 'Student Bills Packages vs Doing It Yourself', 'blog/student-bills-packages-vs-doing-it-yourself-ghu.jpg'],
    ['/blog/what-does-unihomes-do', 'What Does UniHomes Do?', null],
  ];
  const body = `
${hero({
  name: 'Student bills',
  eyebrow: 'Go all in',
  title: 'Go all in for stress-free student bills',
  lead: 'Make uni life a little easier by sorting your household’s utility bills in minutes.',
  actions: `<a class="btn btn-accent btn-lg" href="${quote}">Get a price ${icon('arrowRight')}</a>${r ? `<a class="mk-tp" href="${esc(r.url)}" rel="noopener">${stars(r.stars || 5)}<span><strong>${esc(r.score)}</strong> · ${num(r.total)} reviews on Trustpilot</span></a>` : ''}`,
  extra: `<ul class="bills-icons mk-hero-icons"><li>${icon('flame')}Uncapped gas</li><li>${icon('zap')}Uncapped electricity</li><li>${icon('wifi')}Superfast broadband</li><li>${icon('droplet')}Water</li></ul>`,
})}

<section class="section"><div class="wrap">
  ${sectionHead('', 'Sorted in minutes')}
  ${steps([
    ['Get your price', 'Fill in a few details to get your bespoke price for your student utilities.'],
    ['Add your housemates', 'Share your unique link with your housemates so they can join the account.'],
    ['We sort the rest!', 'Once you’ve all joined, we work with our utility partners to get everything set up so you can have the best time at uni.'],
  ])}
  <p style="margin-top:22px"><a class="btn btn-accent" href="${quote}">Get your price</a></p>
</div></section>

<section class="section section-soft"><div class="wrap">
  ${sectionHead('', 'Bills packages built for students like you')}
  ${tiles(
    [
      { icon: 'home', title: 'Add to any home', text: 'Whether you found your student home with us or elsewhere, our all-inclusive student utilities package can be added to any property.' },
      { icon: 'wifi', title: 'Superfast broadband', text: 'We work with leading suppliers to provide superfast broadband, so you and your housemates can stream your favourite shows, game and study without worries.' },
      { icon: 'flame', title: 'Uncapped energy', text: 'We provide uncapped gas and electricity as standard, so you can use what you need to keep everyone warm, shower, cook, charge devices and more without the stress of an over-usage bill.' },
      { icon: 'layers', title: 'All utilities. One account.', text: 'Instead of dealing with multiple suppliers, setups and phone calls, we take care of everything in one simple monthly payment, split equally between housemates, with no deposits or setup fees.' },
    ],
    'four',
  )}
</div></section>

<section class="section"><div class="wrap mk-split mk-split-img">
  <img class="mk-photo" src="${WP}/2026/02/hero-placeholder-opt-e1776094920759-768x512.jpg" alt="Housemates relaxing at home" loading="lazy">
  <div>
    ${sectionHead('', 'We take the stress out of student utilities')}
    <div class="mk-list">
      <div><h3>${icon('user')}No chief bill payer</h3><p>Rather than having one person responsible for the utilities in your house, we split bills equally between housemates. Each person pays their share and you avoid the awkward housemate chats and chasing others for payments.</p></div>
      <div><h3>${icon('phone')}We're here for you</h3><p>We’re here to make your life at uni as stress-free as possible. We take care of setting things up and we’re always available to help throughout your tenancy.</p></div>
      <div><h3>${icon('sparkles')}More time to focus on the fun stuff</h3><p>Enjoy a year of streaming your favourite shows, gaming, studying, keeping warm, partying, cooking and more, without having to deal with utility companies or worry about an over-usage bill on your energy.</p></div>
    </div>
  </div>
</div></section>

<section class="section-tight"><div class="wrap"><div class="mk-reach mk-wellbeing">
  <div>
    <p class="mk-eyebrow">Included with every package</p>
    <h2>Free 24/7 student wellbeing support for UniHomes customers</h2>
    <p>We’re here to help you make the most of everything uni life has to offer, which is why, once you sign up for an all-inclusive utilities package, you’ll have access to FREE 24/7 wellbeing support via Howden for Students.</p>
    <p>So, if ever things start to feel tough or overwhelming, someone’s always available to make sure you’re ready to take on those deadlines, ace your degree and make lasting memories enjoying stress-free student living all year through.</p>
  </div>
  <div class="mk-wellbeing-badge">${icon('shield')}<strong>24/7</strong><span>wellbeing support</span></div>
</div></div></section>

<section class="section"><div class="wrap">
  <div class="section-head"><div><h2>Our student bills guides</h2></div><a class="link-arrow" href="${href('/blog')}">All posts ${icon('arrowRight')}</a></div>
  <div class="post-grid mk-post-grid">${guides
    .map(
      ([p, t, im]) => `<article class="post"><div class="post-img">${im ? `<img src="${img(im, 640)}" alt="" loading="lazy" width="640" height="360">` : `<div class="mk-post-fallback">${icon('zap')}</div>`}</div><div class="post-body"><h3><a href="${href(p)}">${esc(t)}</a></h3></div></article>`,
    )
    .join('')}</div>
</div></section>

${reviewsRail(r)}

<section class="section-tight"><div class="wrap"><div class="cta-band">
  <div><h2>Ready to GO ALL IN with your utility bills for stress-free student living?</h2><p>Get your bespoke price in minutes — then invite your housemates.</p></div>
  <a class="btn btn-accent btn-lg" href="${quote}">Get a price</a>
</div></div></section>`;
  return { title: pg?.meta?.title || 'Student Bills Packages | UniHomes', description: pg?.meta?.description || 'All-inclusive student utility bills packages: uncapped gas and electricity, superfast broadband and water in one account.', body, head: head() };
}

// --------------------------------------------------------------------- about

const TEAM = [
  ['Phil', 'Co-Founder & CEO'],
  ['Bradley', 'Co-Founder & COO'],
  ['Luca', 'Co-Founder & CRO'],
  ['Ben', 'Chief Financial Officer'],
  ['David', 'Chief Technology and Product Officer'],
  ['Helen', 'Director of Legal and Business Affairs'],
  ['Chris', 'Finance Director'],
  ['India', 'Head of Data & Analytics'],
  ['James', 'Head of Client Relationships and Success'],
  ['Jason', 'Head of Core Platform'],
  ['Lian', 'Head of Marketing'],
  ['Nick', 'Head of Sales'],
  ['Steven', 'Head of CRM'],
  ['Tamaris', 'Head of People and Culture'],
  ['Zander', 'Head of Commercial Strategy and Performance'],
  ['Andrew', 'Head of Partnerships'],
  ['Emma', 'Senior Legal Council'],
  ['Mike', 'Head of Private Rented Sector'],
];

/** Pull the "Our Story" timeline (<p>YEAR</p><p>Title</p><p>…</p>) out of the crawled page. */
function timeline(html) {
  const start = html.indexOf('Our Story');
  if (start < 0) return [];
  const chunk = html.slice(start, html.indexOf('Meet the leadership team') > start ? html.indexOf('Meet the leadership team') : undefined);
  const re = /<p>\s*(20\d\d)\s*<\/p>\s*<p>([^<]+)<\/p>/g;
  const hits = [...chunk.matchAll(re)];
  return hits.map((m, i) => {
    const from = m.index + m[0].length;
    const to = i + 1 < hits.length ? hits[i + 1].index : chunk.search(/<h2>/) > from ? chunk.search(/<h2>/) : chunk.length;
    let body = chunk.slice(from, to).replace(/<h2>[\s\S]*$/, '').trim();
    return { year: m[1], title: m[2].trim(), body };
  });
}

export function about({ pg, rewrite = (h) => h }) {
  const story = timeline(pg?.html || '');
  const body = `
${hero({
  name: 'About',
  eyebrow: 'About UniHomes',
  title: 'We make finding the perfect student home a whole lot simpler.',
  lead: 'UniHomes has been connecting students with their dream property for years. Find out more about us…',
  actions: `<a class="btn btn-white" href="#who-we-work-with">Who we work with</a><a class="btn btn-white" href="#our-story">Our story</a><a class="btn btn-white" href="#meet-the-team">Meet the team</a>`,
})}

<section class="section"><div class="wrap mk-split mk-split-img">
  <div>
    ${sectionHead('', 'Making home hunting simple for students')}
    <p>As ex-students ourselves, we understand how frustrating the student house hunt can be. From hidden fees to low-quality images, finding your dream home while at university can be super difficult. Nevermind having to organise bills once you arrive!</p>
    <p>UniHomes was created to make this process as easy as possible, so you can spend your time doing what matters. We cover <a href="${href('/student-accommodation')}">all major universities and cities</a> in the UK.</p>
    <a class="btn btn-accent" href="${href('/student-accommodation')}">${icon('search')}Find a home</a>
  </div>
  <img class="mk-photo" src="${WP}/2021/05/banner-image-move-in2-min.png" alt="Students moving into their new home" loading="lazy">
</div></section>

<section class="section section-soft" id="who-we-work-with"><div class="wrap mk-split mk-split-img">
  <img class="mk-photo mk-photo-contain" src="${WP}/2021/05/uk-pins-min-838x1024.png" alt="Map of UniHomes cities across the UK" loading="lazy">
  <div>
    ${sectionHead('', "We work with the UK's leading letting agents")}
    <p>For letting agents and landlords, it can be just as challenging to find the perfect tenant for your student property portfolio.</p>
    <p>That’s how UniHomes can help; for years we’ve connected letting agents with thousands of potential tenants. We market your portfolio for you <strong>(for free!)</strong>, so you can focus on growing your business.</p>
    <h3>Interested in advertising with us?</h3>
    <a class="btn btn-primary" href="${href('/partner-with-us')}">Learn more</a>
  </div>
</div></section>

${
  story.length
    ? `<section class="section" id="our-story"><div class="wrap">
  ${sectionHead('', 'Our Story')}
  <ol class="mk-timeline">${story.map((s) => `<li><span class="mk-year">${esc(s.year)}</span><div><h3>${esc(s.title)}</h3><div class="prose">${rewrite(s.body)}</div></div></li>`).join('')}</ol>
</div></section>`
    : ''
}

<section class="section section-soft" id="meet-the-team"><div class="wrap">
  ${sectionHead('', 'Meet the leadership team', 'Meet the incredible team behind the magic at UniHomes. This bunch of passionate, driven and friendly faces will be helping you behind the scenes!')}
  <ul class="mk-team">${TEAM.map(([n, r]) => `<li><span class="mk-avatar" aria-hidden="true">${esc(n[0])}</span><strong>${esc(n)}</strong><span>${esc(r)}</span></li>`).join('')}</ul>
</div></section>

<section class="section-tight"><div class="wrap"><div class="cta-band">
  <div><h2>Interested in joining our amazing team?</h2><p>We’re hiring across marketing, technology, sales, finance and more.</p></div>
  <a class="btn btn-primary btn-lg" href="${href('/careers')}">Check out our careers page</a>
</div></div></section>`;
  return { title: pg?.meta?.title || 'About Us | UniHomes', description: pg?.meta?.description, body, head: head() };
}

// ------------------------------------------------------------------- contact

export function contact({ pg, site }) {
  const help = 'https://help.unihomes.co.uk/';
  const body = `
${hero({ name: 'Contact', eyebrow: 'Contact us', title: 'How can we help?', lead: 'Questions about a property, your bills or your account? Our Help Centre has instant answers — or get in touch with the team.' })}

<section class="section"><div class="wrap">
  <div class="mk-contact">
    <div class="mk-contact-card mk-contact-main">
      <span class="ti">${icon('help')}</span>
      <h2>Help Centre</h2>
      <p>Our Help Centre provides instant answers to common queries about:</p>
      <ul class="subnav">
        <li><a href="https://help.unihomes.co.uk/s/topic/0TOHq000000UUAYOA4/finding-a-home">Finding a home</a></li>
        <li><a href="https://help.unihomes.co.uk/s/topic/0TOHq000000UUAwOAO/signing-for-a-utility-package">Bills packages</a></li>
        <li><a href="https://help.unihomes.co.uk/s/topic/0TOHq000000UUAXOA4/bills-payments">Payments</a></li>
        <li><a href="https://help.unihomes.co.uk/s/global-search/emergencies">Emergencies</a></li>
      </ul>
      <a class="btn btn-accent" href="${help}">Visit the Help Centre ${icon('external')}</a>
    </div>
    <div class="mk-contact-card">
      <span class="ti">${icon('mail')}</span>
      <h2>Email us</h2>
      <p>You can email us at</p>
      <a class="mk-contact-big" href="mailto:customersupport@unihomes.co.uk">customersupport@unihomes.co.uk</a>
    </div>
    <div class="mk-contact-card">
      <span class="ti">${icon('phone')}</span>
      <h2>Call us</h2>
      <p>We're open 9am to 5pm Monday to Friday.</p>
      <a class="mk-contact-big" href="tel:03308220266">0330 822 0266</a>
    </div>
  </div>
</div></section>

<section class="section-tight"><div class="wrap"><div class="cta-band">
  <div><h2>Are you a letting agent looking to fill your student properties?</h2><p>Advertise with bills included and receive high-intent student enquiries.</p></div>
  <a class="btn btn-primary btn-lg" href="${href('/partner-with-us')}">Find out more</a>
</div></div></section>

${reviewsRail(site?.reviews)}

<section class="section-tight"><div class="wrap"><div class="bills">
  <div><h2>Search & compare</h2><p>Thousands of student homes across the UK — every one with bills included.</p></div>
  <ul class="bills-icons"><li>${icon('flame')}Gas</li><li>${icon('zap')}Electricity</li><li>${icon('wifi')}Broadband</li><li>${icon('droplet')}Water</li></ul>
  <a class="btn btn-accent" href="${href('/student-accommodation')}">${icon('search')}Find a home</a>
</div></div></section>`;
  return { title: pg?.meta?.title || 'Contact Us | UniHomes', description: pg?.meta?.description, body, head: head() };
}

// ------------------------------------------------------------------- careers

const ROLES = [
  ['Finance', 'Billing & Collections Manager (15-month FTC)', 'Full Time', 'Sheffield', '/careers/job_20260929134222_YOG4YHHHPS3A4TEP'],
  ['People & Culture', 'Workplace Operations Manager', 'Full Time', 'Sheffield', '/careers/job_20260925150117_OHYEU9BE8WDYVLL3'],
  ['Marketing', 'Senior CRM Marketing Manager', 'Full Time', 'Sheffield', '/careers/job_20260904124533_MCWEG2J6CDZOH59Q'],
  ['Technology', 'Lead Salesforce Implementation Specialist', 'Full Time', 'Sheffield', '/careers/job_20260825083635_YBH6UJJVJ1FKMNJT'],
  ['Sales', 'Account Manager (PBSA/BTR)', 'Full Time', 'Remote', '/careers/job_20260630163311_2L9KINAVEIAIXOG2'],
];

const BENEFITS = [
  ['careers-holiday', 'Additional holiday based on length of service'],
  ['careers-house', 'Hybrid working'],
  ['careers-hearts', 'Voluntary day'],
  ['careers-heartbeat', 'Sick pay'],
  ['careers-compassionate', 'Enhanced compassionate leave including pregnancy loss'],
  ['careers-parents', 'Enhanced maternity & paternity pay'],
  ['careers-hand-heart', 'Menopause support'],
  ['careers-healthcare', 'Healthcare scheme'],
  ['careers-shield', 'Employee Assistance Programme'],
  ['careers-charts', 'Career progression'],
  ['careers-star', 'A commitment to personal and professional development'],
  ['careers-mental-health', 'Mental health support'],
  ['careers-food', 'Complimentary breakfast, hot & cold drinks, snacks'],
  ['careers-socials', 'Company socials'],
  ['careers-refer', 'Refer a friend scheme'],
];

export function careers({ pg }) {
  const body = `
${hero({
  name: 'Careers',
  eyebrow: 'Careers at UniHomes',
  title: "We're looking for passionate, talented and motivated people to join our team",
  lead: 'Join a growing team of marketers, technologists, customer service, sales, finance and people & culture professionals in the heart of Sheffield.',
  actions: `<a class="btn btn-accent btn-lg" href="#available-roles">Open positions</a>`,
  extra: statRow([
    ['2015', 'founded in Sheffield'],
    ['100', 'multi-disciplined professionals'],
    ['3 years', 'Great Place to Work® certified'],
    [String(ROLES.length), 'open roles right now'],
  ]),
})}

<section class="section" id="available-roles"><div class="wrap">
  ${sectionHead('', 'Available roles')}
  <ul class="mk-roles">${ROLES.map(
    ([dept, title, type, loc, path]) =>
      `<li><a href="${live(path)}"><span class="mk-dept">${esc(dept)}</span><strong>${esc(title)}</strong><span class="mk-role-meta">${icon('clock')}${esc(type)} ${icon('pin')}${esc(loc)}</span><span class="mk-role-go">${icon('arrowRight')}</span></a></li>`,
  ).join('')}</ul>
  <p class="muted" style="margin-top:14px;font-size:.9rem">Applications are handled on unihomes.co.uk · <a href="https://cdn-p1.unihomes.co.uk/documents/careers/unihomes-candidate-privacy-notice.pdf">View candidate privacy policy</a></p>
</div></section>

<section class="section section-soft"><div class="wrap mk-split">
  <div>
    ${sectionHead('', 'Who we are')}
    <p>UniHomes is the leading student property search portal and shared utility management service, helping students find their ideal accommodation with bills included.</p>
    <p>Founded in 2015 by three local Sheffield ex-students and industry professionals, we’ve grown significantly and now advertise thousands of student properties across 50 major towns and cities in the UK. We acquired Split The Bills in 2020 which bolstered our bills inclusive offer to students across the UK.</p>
  </div>
  <div>
    ${sectionHead('', 'What’s it like working here?')}
    <p>People are our power, so it’s important we provide the right environment to nurture our talent. You’ll work in our stunning city centre office with panoramic views of Sheffield. We’ll ensure you are fully supported in your role, giving you the ability to grow and develop within the business.</p>
    <p class="mk-eyebrow mk-eyebrow-dark" style="margin-top:18px">Our staff say</p>
    <ul class="mk-chips">${['there’s a great team spirit', 'inclusive', 'a company that cares about its people', 'a growing and forward-thinking company', 'opportunity to make a tangible impact', 'collaborative', 'local friendly business and team', 'great people work here']
      .map((q) => `<li>“${esc(q)}”</li>`)
      .join('')}</ul>
  </div>
</div></section>

<section class="section"><div class="wrap"><div class="mk-gptw">
  <img src="${CDN0}/images/unihomes-great-place-to-work-badge.png" alt="UniHomes — Great Place to Work certified" width="140" loading="lazy">
  <div>
    <h2>Great Place to Work®!</h2>
    <p>It’s official! Thanks to our fantastic people, we’ve been certified as a Great Place to Work® 2025-2026 for the third year in a row!</p>
    <blockquote class="mk-tile-quote"><p>“The company culture at UniHomes is a breath of fresh air. I enjoy coming into work which is something I never thought I'd say.”</p><footer>UniHomes team member</footer></blockquote>
  </div>
</div></div></section>

<section class="section section-soft"><div class="wrap">
  ${sectionHead('', 'Benefits', 'At UniHomes, our people are our greatest asset, and we want to ensure that we create a safe and warm place for you to grow. Here are some of our benefits.')}
  <ul class="mk-benefits">${BENEFITS.map(([f, t]) => `<li><img src="${CDN0}/svg/${f}.svg" alt="" width="40" height="40" loading="lazy"><span>${esc(t)}</span></li>`).join('')}</ul>
</div></section>

<section class="section-tight"><div class="wrap"><div class="cta-band">
  <div><h2>Ready to join us?</h2><p>See the latest openings and apply on unihomes.co.uk.</p></div>
  <a class="btn btn-accent btn-lg" href="#available-roles">View open positions</a>
</div></div></section>`;
  return { title: pg?.meta?.title || 'Careers at UniHomes | UniHomes', description: pg?.meta?.description, body, head: head() };
}
